

theme: jekyll-theme-cayman

nav1:
  name: "Guides"
  url: "guides/"

nav2:
  name: "Hobbiton Discord"
  url: "https://discord.gg/aQnrnQeYt7"


- name: Github Pages Directory Listing
  uses: jayanta525/github-pages-directory-listing@v4.0.0